### ISSUE TITLE
NetworkInterface may have multiple ip addresses.

### ISSUE THREAD

**Issue by mokeyish** [EstebanBorai/network-interface#30] opened 2022-12-22 14:27 UTC
IPv4 and IPv6 address may exist on the same network interface. But 
https://github.com/EstebanBorai/network-interface/blob/bb5527352ae9e694afd50a09a7cea5b85e0d8604/src/interface.rs#L17

Please refer here
https://github.com/dotnet/runtime/blob/84b839e7c50de58a9d92fe0e3ed235630ee12fff/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkInterface.cs#L64

https://stackoverflow.com/questions/9855230/how-do-i-get-the-network-interface-and-its-right-ipv4-address

**Comment by RReverser** [comment] 2023-05-01 22:20
Duplicate of #26, see https://github.com/EstebanBorai/network-interface/issues/26#issuecomment-1530432906.

**Comment by EstebanBorai** [comment] 2023-05-01 23:48
Closing as completed! Thanks for sharing @RReverser!

**Closed by EstebanBorai** 2023-05-01 23:48 UTC
